apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    tier: database
  name: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - image: registry.access.redhat.com/rhscl/mysql-56-rhel7:latest
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: pricelist
        - name: MYSQL_PASSWORD
          value: pricelist
        - name: MYSQL_USER
          value: pricelist
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-db
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          exec:
            command: [ "sh", "-c", "/opt/rh/rh-mysql56/root/usr/bin/mysql", "--user=$MYSQL_USER", "--password=$MYSQL_PASSWORD", "--host=$(hostname)", "-e", 'SELECT 1;' ]
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: mysql-db
        persistentVolumeClaim:
          claimName: pricelist-db-pvc
