apiVersion: batch/v1
kind: Job
metadata:
  name: pricelist-postdeploy
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    metadata:
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          until [ $(curl -s -o /dev/null -w "%{http_code}" http://pricelist:8080/create_database.php) -eq 200 ]; do sleep 5; done
          curl -s http://pricelist:8080/create_database.php
        image: quay.io/redhatworkshops/pricelist:latest
        name: pricelist-postdeploy
      restartPolicy: Never
